services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__ProductsCollection=Products
      - DatabaseSettings__BrandsCollection=Brands
      - DatabaseSettings__TypesCollection=Types
    depends_on:
      catalogdb:
        condition: service_healthy
    ports:
      - "9000:8080"
      - "9001:8081"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro