services:
#CatalogDB
  catalogdb:
    image: mongo
#Catalog.API
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

volumes:
 mongo_data:


