services:

 #Catalogdb
  catalogdb:
    image: mongo

 #Catalog.API
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/Catalog/Catalog.Api/Dockerfile


  #discountdb
  discountdb:
      image: postgres:16-alpine

  #PostgresAdmin
  pgadmin:
      image: dpage/pgadmin4


 #Basketdb
  basketdb:
    image: redis
 #Basket.API
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/basket/Basket.Api/Dockerfile

 #Discount.API
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: services/Discount/Discount.Api/Dockerfile

volumes:
  mongo_data:
  discount_data:
  pgadmin_data:

