<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Mapster" Version="10.0.11" />
        <PackageReference Include="Mapster.DependencyInjection" Version="10.0.11" />

        <PackageReference Include="MediatR" Version="12.5.0" />

        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />

        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ordering.Core\Ordering.Core.csproj" />
                <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
</ItemGroup>

</Project>
